version: "2"
services:
  fulfillment-ui:
    image: openlmis/dev-ui:7.0.0-SNAPSHOT
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - cce-ui
    depends_on:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - cce-ui
  auth-ui:
    image: openlmis/auth-ui:6.1.0-SNAPSHOT
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.3.0-SNAPSHOT
    volumes:
      - '/openlmis-referencedata-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:1.1.0-SNAPSHOT
    volumes:
     - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:5.3.0-SNAPSHOT
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.0-SNAPSHOT
    volumes:
      - '/openlmis-ui-layout'
  cce-ui:
    image: openlmis/cce-ui:1.0.0-SNAPSHOT
    volumes:
      - '/openlmis-cce-ui'
  image:
    build: .
    image: openlmis/fulfillment-ui
